import json,time,urllib.request,urllib.parse,os,sys
from pathlib import Path
from datetime import datetime
def load_env():
    e={}
    try:
        for l in Path(".env.local").read_text().splitlines():
            l=l.strip()
            if l and not l.startswith("#") and "=" in l:
                k,_,v=l.partition("="); e[k.strip()]=v.strip().strip('"').strip("'")
    except: pass
    return e
env=load_env()
KEY=env.get("AIRTABLE_API_KEY",""); BASE="appaVFVbwG9MkoDa9"; TABLE="Haya_Content"; TODAY=datetime.now().strftime("%Y-%m-%d")
H={"Authorization":f"Bearer {KEY}","Content-Type":"application/json"}
CONTENT=[
{"content_id":"skincare-routine-guide","content_tier":"pillar","category":"Skincare","title":"The Complete Guide to Building a Skincare Routine","meta_title":"How to Build a Skincare Routine","meta_description":"Step-by-step guide to cleansing, toning, serums, moisturising and SPF for any skin type.","keywords":"skincare routine, cleanser, toner, serum, moisturiser, SPF","status":"published","word_count":870,"body":"## The Core Steps\n\nA skincare routine works when you apply the right products in the right order. The fundamentals are the same for every skin type: cleanse, treat, moisturise, protect.\n\n## Step 1: Cleanser\n\nUse a gentle cleanser suited to your skin type morning and evening. Gel or foam for oily skin, cream or milk for dry skin, fragrance-free for sensitive skin.\n\n## Step 2: Toner\n\nA toner balances pH and preps skin to absorb serums. Look for hyaluronic acid for hydration or niacinamide for pore refinement.\n\n## Step 3: Serum\n\nTargeted treatment. Vitamin C for pigmentation, retinol for fine lines, hyaluronic acid for dehydration, niacinamide for acne. Apply thinnest serum first.\n\n## Step 4: Moisturiser\n\nAll skin types need moisturiser. Lightweight gel for oily, rich cream with ceramides for dry skin.\n\n## Step 5: SPF (Morning Only)\n\nSPF 30 minimum, SPF 50+ preferred. Last step every morning. UV causes 80% of visible skin ageing."},
{"content_id":"serums-actives-guide","content_tier":"pillar","category":"Serums & Actives","title":"Understanding Serums and Active Ingredients","meta_title":"Serums and Active Ingredients: The Complete Guide","meta_description":"Everything about vitamin C, retinol, hyaluronic acid, niacinamide, AHAs and BHAs explained simply.","keywords":"skincare serums, vitamin C, retinol, hyaluronic acid, niacinamide, AHA BHA","status":"published","word_count":850,"body":"## What Is a Serum?\n\nSerums are lightweight concentrated formulations that deliver active ingredients deep into the skin. Smaller molecules than moisturisers mean deeper penetration and faster results.\n\n## Vitamin C\n\nBrightens, fades dark spots, stimulates collagen. Use in the morning. 10-20% concentration. Store in a dark cool place.\n\n## Retinol\n\nGold standard anti-ageing. Accelerates cell turnover, fades pigmentation, smooths lines. Use at night only. Start once per week and build slowly.\n\n## Hyaluronic Acid\n\nHolds 1000x its weight in water. Apply to damp skin, follow with moisturiser. Suitable for all skin types.\n\n## Niacinamide\n\nMinimises pores, controls oil, fades pigmentation, strengthens barrier. 10% concentration. Pairs well with most actives.\n\n## AHAs and BHAs\n\nAHAs exfoliate the surface. BHAs penetrate pores for acne and blackheads. Use 2-3 times per week maximum. Always follow with SPF."},
{"content_id":"sun-protection-guide","content_tier":"pillar","category":"Sun Care","title":"Sun Protection 101: SPF, UVA and UVB Explained","meta_title":"SPF Guide: UVA, UVB and Choosing the Right Sunscreen","meta_description":"Everything you need to know about SPF numbers, UVA vs UVB, and how much sunscreen to apply.","keywords":"SPF guide, UVA UVB, mineral vs chemical sunscreen, daily sunscreen","status":"published","word_count":720,"body":"## Why Sunscreen Matters\n\nUV radiation causes up to 80% of visible skin ageing. Sunscreen is the single most impactful skincare step you can take.\n\n## UVA vs UVB\n\nUVB causes sunburn. UVA penetrates deeper causing ageing and long-term damage. Always choose broad spectrum protection.\n\n## What Does SPF Mean?\n\nSPF 30 blocks 97% of UVB. SPF 50 blocks 98%. The number matters less than how much you apply and whether you reapply.\n\n## Physical vs Chemical Sunscreen\n\nPhysical sunscreens contain zinc oxide or titanium dioxide and sit on the skin. Chemical sunscreens absorb UV and convert it to heat. Both work well.\n\n## How Much to Apply\n\nOne quarter teaspoon for the face. Reapply every two hours outdoors."},
{"content_id":"body-care-guide","content_tier":"pillar","category":"Body & Hair","title":"Body Care Essentials: The Complete Routine","meta_title":"Body Care Routine: Products and Steps","meta_description":"How to build a body care routine from cleansing and exfoliating to moisturising and hair care.","keywords":"body care routine, body moisturiser, body scrub, hair care routine","status":"published","word_count":680,"body":"## Why Body Care Matters\n\nBody skin covers 99% of your surface area but is often neglected. A simple three-step routine makes a visible difference within weeks.\n\n## Step 1: Cleanse\n\nA body wash replaces harsh soap. Choose cream for dry skin, gel for normal skin, salicylic acid formula for acne-prone back and chest.\n\n## Step 2: Exfoliate\n\nTwo to three times per week. Sugar or coffee scrubs remove dead cells and improve moisturiser absorption dramatically.\n\n## Step 3: Moisturise\n\nApply within three minutes of showering while skin is still damp. Body lotion for everyday use, body butter for very dry skin, body oil for glow.\n\n## Hair Care Basics\n\nWash every two to three days. Conditioner from mid-lengths to ends. Weekly hair mask for dry or damaged hair. Argan oil serum on damp hair before drying."},
{"content_id":"pro-skincare-tools","content_tier":"pillar","category":"Pro Tools","title":"Professional Skincare Tools That Actually Work","meta_title":"Best Skincare Tools: Devices That Actually Work","meta_description":"A no-hype guide to derma rollers, LED masks, microcurrent devices and gua sha.","keywords":"skincare tools, derma roller, LED face mask, microcurrent device, gua sha","status":"published","word_count":800,"body":"## Derma Rollers\n\nTiny needles create micro-injuries that trigger collagen production. Evidence supports improved texture and reduced fine lines. Use 0.5mm at home one to two times per week. Always apply hyaluronic acid serum immediately after.\n\n## LED Light Therapy Masks\n\nRed light stimulates collagen and reduces inflammation. Blue light kills acne bacteria. Use three to five sessions per week for best results over eight to twelve weeks.\n\n## Microcurrent Devices\n\nLow-level electrical currents stimulate facial muscles and improve contour. Results require consistency - five sessions per week initially. Think of it as a facial workout.\n\n## Gua Sha\n\nImproves lymphatic drainage, reduces puffiness and relieves facial tension. Apply face oil first. Use gentle upward and outward strokes. Results are immediate rather than cumulative.\n\n## What to Buy First\n\nLED mask for broadest benefit, gua sha for immediate results, derma roller for collagen stimulation."},
{"content_id":"cosmetics-guide","content_tier":"pillar","category":"Cosmetics","title":"Cosmetics and Colour: Choosing Products for Your Skin","meta_title":"How to Choose Cosmetics for Your Skin Type and Tone","meta_description":"How to choose foundation, concealer, blush and colour cosmetics for your skin type and undertone.","keywords":"how to choose foundation, undertone guide, cosmetics for skin type","status":"published","word_count":740,"body":"## Finding Your Undertone\n\nUndertone matters more than skin tone when choosing foundation. Warm undertones are yellow or golden. Cool undertones are pink or blue. Neutral is a balance of both. Check your inner wrist veins: blue means cool, green means warm.\n\n## Choosing Foundation\n\nMatch your jawline exactly. Matte formula for oily skin, hydrating formula for dry skin, satin finish for combination. Sheer coverage for natural look, full coverage for events.\n\n## Concealer\n\nOne to two shades lighter than foundation for under eyes. Exact match for blemishes.\n\n## Blush and Bronzer\n\nPeach and coral for warm undertones. Rose and berry for cool. Bronzer two to three shades darker than skin tone applied where sun naturally hits.\n\n## Setting and Longevity\n\nTranslucent setting powder prevents transfer. Setting spray extends wear and adds natural finish."},
{"content_id":"physical-vs-chemical-sunscreen","content_tier":"comparison","category":"Sun Care","title":"Physical vs Chemical Sunscreen: Which Is Right for You?","meta_title":"Physical vs Chemical Sunscreen: Which Should You Choose?","meta_description":"Side-by-side comparison of mineral and chemical sunscreen - how they work, pros, cons and best skin types.","keywords":"physical vs chemical sunscreen, mineral sunscreen, zinc oxide","status":"published","word_count":580,"body":"## The Difference\n\nPhysical sunscreens contain zinc oxide or titanium dioxide and reflect UV rays. Chemical sunscreens absorb UV and convert it to heat.\n\n## Physical Sunscreen\n\nWorks immediately on application. Good for sensitive skin, pregnancy and children. Reef-safe. Can leave white cast on deeper skin tones.\n\n## Chemical Sunscreen\n\nNo white cast. Lightweight texture. Needs 20 minutes before sun exposure. Wide range of high SPF formulas available.\n\n## The Verdict\n\nNeither is universally better. Sensitive skin, pregnancy or outdoor water activity - choose mineral. Deeper skin tone or daily commuting - chemical is more practical. Many modern formulas blend both types."},
{"content_id":"vitamin-c-vs-niacinamide","content_tier":"comparison","category":"Serums & Actives","title":"Vitamin C vs Niacinamide: Which Brightening Serum Wins?","meta_title":"Vitamin C vs Niacinamide: Which Should You Use?","meta_description":"Comparing vitamin C and niacinamide serums - how they work, what they target, and whether you can use both.","keywords":"vitamin C vs niacinamide, brightening serum, can you use vitamin C and niacinamide together","status":"published","word_count":540,"body":"## Two Different Mechanisms\n\nBoth brighten skin but work differently. Vitamin C inhibits melanin production. Niacinamide reduces melanin transfer to skin cells.\n\n## Vitamin C\n\nPowerful antioxidant and brightener. Best in the morning under SPF. 10-20% concentration. Unstable - store carefully.\n\n## Niacinamide\n\nMore versatile. Also minimises pores, controls oil and strengthens barrier. Very stable. Suitable for all skin types twice daily.\n\n## Can You Use Both?\n\nYes. Modern research shows they work well together. Use niacinamide morning and evening. Add vitamin C in the morning for antioxidant protection.\n\n## Which to Choose First\n\nNiacinamide is more versatile and forgiving for beginners. Vitamin C adds superior antioxidant protection. Ideal: use both, niacinamide daily and vitamin C in the morning."},
]
def exists(cid):
    f=urllib.parse.quote(f"{{content_id}}='{cid}'")
    url=f"https://api.airtable.com/v0/{BASE}/{TABLE}?filterByFormula={f}&maxRecords=1"
    req=urllib.request.Request(url,headers=H)
    with urllib.request.urlopen(req) as r: data=json.loads(r.read())
    return len(data.get("records",[]))>0
def create(fields):
    url=f"https://api.airtable.com/v0/{BASE}/{TABLE}"
    body=json.dumps({"records":[{"fields":fields}]}).encode()
    req=urllib.request.Request(url,data=body,headers=H,method="POST")
    with urllib.request.urlopen(req) as r: return json.loads(r.read())
print(f"\nSeeding Haya_Content — {len(CONTENT)} pages\n")
created=skipped=errors=0
for item in CONTENT:
    try:
        if exists(item["content_id"]):
            print(f"  SKIP  {item['content_id']}"); skipped+=1; time.sleep(0.2); continue
        fields={**item,"published_at":TODAY,"last_updated":TODAY}
        create(fields); print(f"  OK    {item['content_id']}"); created+=1; time.sleep(0.3)
    except Exception as e:
        print(f"  ERR   {item['content_id']}: {e}"); errors+=1; time.sleep(0.5)
print(f"\nCreated:{created}  Skipped:{skipped}  Errors:{errors}")
