import { Product, Category } from './types'

export const CATEGORIES: Category[] = [
  {
    id: 'infection-control',
    label: 'Infection Control',
    labelAr: 'مكافحة العدوى',
    icon: 'infection-control',
    description: 'Disinfectants, sanitizers, surface wipes and barrier protection',
    productCount: 5,
    color: '#0D0D0D',
  },
  {
    id: 'dental-supplies',
    label: 'Dental Supplies',
    labelAr: 'المستلزمات طب الأسنان',
    icon: 'dental-supplies',
    description: 'Instruments, consumables and restorative dental materials',
    productCount: 4,
    color: '#0052A3',
  },
  {
    id: 'medical-devices',
    label: 'Medical Devices',
    labelAr: 'الأجهزة الطبية',
    icon: 'ppe',
    description: 'Disposables, wound care and clinical consumables',
    productCount: 3,
    color: '#1976D2',
  },
  {
    id: 'ppe',
    label: 'PPE',
    labelAr: 'معدات الوقاية الشخصية',
    icon: 'diagnostics',
    description: 'Gloves, masks, gowns and eye protection',
    productCount: 4,
    color: '#2196F3',
  },
  {
    id: 'diagnostics',
    label: 'Diagnostics',
    labelAr: 'التشخيص',
    icon: 'sterilization',
    description: 'Monitoring devices, thermometers and diagnostic equipment',
    productCount: 3,
    color: '#D4891A',
  },
  {
    id: 'sterilization',
    label: 'Sterilization',
    labelAr: 'التعقيم',
    icon: 'medical-devices',
    description: 'Autoclaves, pouches, indicators and sterilization equipment',
    productCount: 3,
    color: '#F5A623',
  },
]

export const PRODUCTS: Product[] = [
  // ─── INFECTION CONTROL ──────────────────────────────────────────────────────
  {
    id: 'IC-001',
    name: 'SterioWipe Surface Disinfectant Wipes',
    nameAr: 'مناديل تطهير الأسطح ستيريووايب',
    sku: 'HS-IC-001',
    category: 'infection-control',
    subcategory: 'Surface Disinfection',
    description: 'Alcohol-based ready-to-use surface disinfectant wipes. Effective against bacteria, fungi and enveloped viruses including MRSA, HBV, HIV. EN14476 & EN13727 certified. Ideal for clinical surfaces, medical equipment and dental units.',
    descriptionAr: 'مناديل تطهير جاهزة للاستخدام تعتمد على الكحول. فعّالة ضد البكتيريا والفطريات والفيروسات المغلّفة.',
    price: 5.200,
    priceVat: 5.460,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=SterioWipe',
      'https://placehold.co/600x600/E6EFF8/003B73?text=SterioWipe+Pack',
    ],
    stock: 150,
    unit: 'canister',
    unitSize: '200 wipes',
    brand: 'SterioMed',
    origin: 'Germany',
    tags: ['disinfectant', 'surface', 'wipes', 'alcohol', 'EN14476'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['EN 14476', 'EN 13727', 'CE'],
    relatedIds: ['IC-002', 'IC-003', 'PPE-001'],
    createdAt: '2024-01-15',
  },
  {
    id: 'IC-002',
    name: 'NexaClean Alcohol Hand Rub 500ml',
    nameAr: 'هيات كلين محلول اليد الكحولي 500 مل',
    sku: 'HS-IC-002',
    category: 'infection-control',
    subcategory: 'Hand Hygiene',
    description: 'WHO-formulated alcohol-based hand rub with 75% ethanol. Quick-drying, non-sticky formula with added emollients to prevent skin dryness. Pump dispenser bottle. Ideal for high-frequency use in clinical environments.',
    descriptionAr: 'محلول يدوي كحولي وفق صيغة منظمة الصحة العالمية بنسبة 75% إيثانول.',
    price: 2.800,
    priceVat: 2.940,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=Hand+Rub+500ml',
      'https://placehold.co/600x600/E6EFF8/003B73?text=NexaClean',
    ],
    stock: 300,
    unit: 'bottle',
    unitSize: '500ml',
    brand: 'NexaClean',
    origin: 'Oman',
    tags: ['hand sanitizer', 'alcohol', 'WHO formula', 'hygiene'],
    featured: true,
    inStock: true,
    minOrderQty: 12,
    packaging: 'Carton of 12 bottles',
    certifications: ['WHO Formulation', 'ISO 13485'],
    relatedIds: ['IC-001', 'IC-004'],
    createdAt: '2024-02-01',
  },
  {
    id: 'IC-003',
    name: 'AlcoGel Professional Hand Rub 1000ml',
    nameAr: 'الكوجيل محلول اليد المهني 1000 مل',
    sku: 'HS-IC-003',
    category: 'infection-control',
    subcategory: 'Hand Hygiene',
    description: 'Professional-grade 1-litre wall-mount dispenser refill. 80% isopropanol content. Compatible with standard push-top dispensers. Kills 99.99% of common germs and pathogens. Preferred for clinic reception and corridor points.',
    descriptionAr: 'عبوة إعادة ملء بسعة لتر واحد للموزعات الجدارية. محتوى الإيزوبروبانول 80%.',
    price: 4.200,
    priceVat: 4.410,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=AlcoGel+1L',
    ],
    stock: 220,
    unit: 'bottle',
    unitSize: '1000ml',
    brand: 'AlcoGel',
    origin: 'UAE',
    tags: ['hand rub', 'isopropanol', '1L', 'refill', 'wall dispenser'],
    featured: false,
    inStock: true,
    minOrderQty: 6,
    certifications: ['EN 1500'],
    relatedIds: ['IC-002'],
    createdAt: '2024-02-10',
  },
  {
    id: 'IC-004',
    name: 'SafeBarrier Level 3 Surgical Masks',
    nameAr: 'قناع جراحي مستوى 3 سيف باريير',
    sku: 'HS-IC-004',
    category: 'infection-control',
    subcategory: 'Face Protection',
    description: 'ASTM Level 3 three-ply surgical face masks with adjustable nose wire. BFE ≥98%, PFE ≥98%. Fluid resistant. Individually wrapped in sealed pouches. Ideal for surgical procedures and high-splatter environments.',
    descriptionAr: 'أقنعة وجه جراحية ثلاثية الطبقات معتمدة ASTM Level 3.',
    price: 4.500,
    priceVat: 4.725,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=Surgical+Masks',
    ],
    stock: 500,
    unit: 'box',
    unitSize: '50 pcs',
    brand: 'SafeBarrier',
    origin: 'Malaysia',
    tags: ['surgical mask', 'ASTM Level 3', 'face protection', 'BFE'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['ASTM F2100 Level 3', 'EN 14683'],
    relatedIds: ['PPE-002', 'PPE-001'],
    createdAt: '2024-01-20',
  },
  {
    id: 'IC-005',
    name: 'QuatroCide HD Instrument Disinfectant 5L',
    nameAr: 'كواتروسيد HD مطهر الأدوات 5 لتر',
    sku: 'HS-IC-005',
    category: 'infection-control',
    subcategory: 'Instrument Disinfection',
    description: 'High-level instrument disinfectant and sterilant. Glutaraldehyde-free formula. Active against bacteria, fungi, mycobacteria and viruses. 30-minute immersion for high-level disinfection. Suitable for heat-sensitive instruments and endoscopes.',
    descriptionAr: 'مطهر ومعقم للأدوات على مستوى عالٍ. خالٍ من الجلوتارالديهايد.',
    price: 18.500,
    priceVat: 19.425,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=QuatroCide+5L',
    ],
    stock: 80,
    unit: 'container',
    unitSize: '5 Litres',
    brand: 'QuatroCide',
    origin: 'UK',
    tags: ['instrument disinfection', 'high level', 'glutaraldehyde-free', 'endoscope'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['EN 13727', 'EN 14348', 'EN 14476'],
    relatedIds: ['ST-001', 'ST-002'],
    createdAt: '2024-03-05',
  },

  // ─── DENTAL SUPPLIES ────────────────────────────────────────────────────────
  {
    id: 'DS-001',
    name: 'ProDent Premium Extraction Forceps Set',
    nameAr: 'طقم ملقاط الخلع بروديانت',
    sku: 'HS-DS-001',
    category: 'dental-supplies',
    subcategory: 'Surgical Instruments',
    description: 'Full-mouth extraction forceps set — 10 pieces. Crafted from 420-grade stainless steel with precision-ground beaks. Includes upper anteriors, upper posteriors, lower anteriors, lower posteriors, upper and lower molar variants, and cow-horn forceps. Autoclavable. Supplied in sterilization tray.',
    descriptionAr: 'طقم ملقاط خلع للفم الكامل — 10 قطع. مصنوع من الفولاذ المقاوم للصدأ الدرجة 420.',
    price: 45.000,
    priceVat: 47.250,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/002A54/FFFFFF?text=Forceps+Set',
      'https://placehold.co/600x600/E6EFF8/003B73?text=ProDent+Instruments',
    ],
    stock: 25,
    unit: 'set',
    unitSize: '10 pieces',
    brand: 'ProDent',
    origin: 'Germany',
    tags: ['forceps', 'extraction', 'dental instruments', 'stainless steel', 'autoclavable'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['DS-004', 'ST-001'],
    createdAt: '2024-01-10',
  },
  {
    id: 'DS-002',
    name: 'DentalShield Nano Composite Resin Kit',
    nameAr: 'كيت الراتنج المركب النانوي دينتال شيلد',
    sku: 'HS-DS-002',
    category: 'dental-supplies',
    subcategory: 'Restorative Materials',
    description: 'Universal nano-hybrid composite resin system. 12 VITA shades + incisal variants. High polish retention, exceptional wear resistance. Radiopaque. Low volumetric shrinkage (≤1.9%). Ideal for Class I–V restorations. Includes 12 × 4g syringes, shade guide, instructions.',
    descriptionAr: 'نظام راتنج مركب نانوي عالمي. 12 درجة VITA + متغيرات القاطع. احتفاظ عالٍ بالتلميع.',
    price: 78.500,
    priceVat: 82.425,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/002A54/FFFFFF?text=Composite+Kit',
    ],
    stock: 18,
    unit: 'kit',
    unitSize: '12 × 4g syringes',
    brand: 'DentalShield',
    origin: 'Switzerland',
    tags: ['composite', 'resin', 'restorative', 'VITA shades', 'nano-hybrid'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'ISO 4049'],
    relatedIds: ['DS-001', 'DS-003'],
    createdAt: '2024-02-20',
  },
  {
    id: 'DS-003',
    name: 'DentalPro Ultrasonic Scaler Handpiece',
    nameAr: 'رأس المقياس بالموجات فوق الصوتية دينتال برو',
    sku: 'HS-DS-003',
    category: 'dental-supplies',
    subcategory: 'Scaling & Prophylaxis',
    description: 'Magnetostrictive ultrasonic scaler insert compatible with Dentsply Cavitron and most universal slim handpieces. Standard frequency 30kHz. Comes with 3 tip types: general scaling, periodontal, and furcation. Autoclavable titanium tip.',
    descriptionAr: 'رأس مقياس بالموجات فوق الصوتية المغناطيسية متوافق مع كافيترون دنتسبلاي.',
    price: 95.000,
    priceVat: 99.750,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/002A54/FFFFFF?text=Ultrasonic+Scaler',
    ],
    stock: 12,
    unit: 'piece',
    unitSize: 'Includes 3 tips',
    brand: 'DentalPro',
    origin: 'USA',
    tags: ['ultrasonic scaler', 'periodontal', 'scaling', 'prophylaxis', 'titanium'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'FDA', 'ISO 13485'],
    relatedIds: ['DS-001', 'DS-004'],
    createdAt: '2024-01-28',
  },
  {
    id: 'DS-004',
    name: 'Lidocaine Anesthetic Carpules 1.8ml',
    nameAr: 'أمبولات تخدير ليدوكايين 1.8 مل',
    sku: 'HS-DS-004',
    category: 'dental-supplies',
    subcategory: 'Local Anaesthesia',
    description: '2% Lidocaine HCl with 1:100,000 Epinephrine. 1.8ml glass carpules, packaged 50 per box. Sterile, latex-free. For infiltration and nerve block techniques. Long-acting formulation for complex procedures. Meets ISO 11135 sterility standards.',
    descriptionAr: '2% هيدروكلوريد الليدوكايين مع 1:100,000 إبينفرين. أمبولات زجاجية 1.8 مل.',
    price: 32.000,
    priceVat: 33.600,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/002A54/FFFFFF?text=Anesthetic+Carpules',
    ],
    stock: 60,
    unit: 'box',
    unitSize: '50 carpules',
    brand: 'DentoCaine',
    origin: 'France',
    tags: ['lidocaine', 'anesthetic', 'carpules', 'epinephrine', 'nerve block'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'ISO 11135'],
    relatedIds: ['DS-001', 'DS-003'],
    createdAt: '2024-02-14',
  },

  // ─── PPE ────────────────────────────────────────────────────────────────────
  {
    id: 'PPE-001',
    name: 'EG-Safe Nitrile Examination Gloves',
    nameAr: 'قفازات فحص نيتريل إيجي سيف',
    sku: 'HS-PPE-001',
    category: 'ppe',
    subcategory: 'Examination Gloves',
    description: 'Powder-free, textured fingertip nitrile examination gloves. AQL 1.5 quality rating. 3.5 mil thickness. Beaded cuff for easy donning. Chemo-rated for use with chemotherapy agents. Available in S/M/L/XL. Latex-free, suitable for latex-allergic personnel.',
    descriptionAr: 'قفازات فحص نيتريل خالية من البودرة. تقييم الجودة AQL 1.5. سماكة 3.5 ميل.',
    price: 3.500,
    priceVat: 3.675,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=Nitrile+Gloves',
      'https://placehold.co/600x600/E6EFF8/003B73?text=EG-Safe+Box',
    ],
    stock: 400,
    unit: 'box',
    unitSize: '100 pcs',
    brand: 'EG-Safe',
    origin: 'Malaysia',
    tags: ['nitrile', 'gloves', 'examination', 'powder-free', 'latex-free', 'chemo'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    packaging: 'Carton of 10 boxes',
    certifications: ['EN 455', 'ASTM D6319', 'EN 374', 'FDA 510(k)'],
    relatedIds: ['PPE-002', 'PPE-003', 'IC-001'],
    createdAt: '2024-01-05',
  },
  {
    id: 'PPE-002',
    name: 'IsoShield N95 Respirator Masks',
    nameAr: 'قناع مرشح N95 آيزو شيلد',
    sku: 'HS-PPE-002',
    category: 'ppe',
    subcategory: 'Respiratory Protection',
    description: 'NIOSH-approved N95 filtering facepiece respirator. ≥95% filtration efficiency for non-oil-based particles. Cup-style design with adjustable nose clip and dual head-straps. Low breathing resistance. Individually bagged. Suitable for TB, COVID-19 and airborne pathogen environments.',
    descriptionAr: 'قناع تنفسي N95 معتمد من NIOSH. كفاءة تصفية ≥95% للجسيمات غير الزيتية.',
    price: 8.900,
    priceVat: 9.345,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=N95+Respirator',
    ],
    stock: 200,
    unit: 'box',
    unitSize: '20 pcs',
    brand: 'IsoShield',
    origin: 'USA',
    tags: ['N95', 'respirator', 'NIOSH', 'airborne', 'TB', 'COVID'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['NIOSH', 'GB 2626', 'FDA EUA'],
    relatedIds: ['PPE-001', 'IC-004'],
    createdAt: '2024-01-12',
  },
  {
    id: 'PPE-003',
    name: 'ShieldPro Safety Goggles',
    nameAr: 'نظارات السلامة شيلد برو',
    sku: 'HS-PPE-003',
    category: 'ppe',
    subcategory: 'Eye Protection',
    description: 'Indirect ventilated safety goggles for splash and droplet protection. Anti-fog polycarbonate lens. EN166 1B 3 4 certified. Adjustable headband. Can be worn over prescription glasses. Autoclavable. Reusable with alcohol disinfection.',
    descriptionAr: 'نظارات سلامة ذات تهوية غير مباشرة. عدسة بولي كربونات مضادة للضباب.',
    price: 3.200,
    priceVat: 3.360,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=Safety+Goggles',
    ],
    stock: 180,
    unit: 'piece',
    unitSize: 'One size',
    brand: 'ShieldPro',
    origin: 'Italy',
    tags: ['goggles', 'eye protection', 'EN166', 'anti-fog', 'reusable'],
    featured: false,
    inStock: true,
    minOrderQty: 5,
    certifications: ['EN 166', 'CE'],
    relatedIds: ['PPE-001', 'PPE-002'],
    createdAt: '2024-02-08',
  },
  {
    id: 'PPE-004',
    name: 'SurgiShield Sterile Surgical Gloves Sz 7.5',
    nameAr: 'قفازات جراحية معقمة سيرجي شيلد مقاس 7.5',
    sku: 'HS-PPE-004',
    category: 'ppe',
    subcategory: 'Surgical Gloves',
    description: 'Sterile powder-free natural rubber latex surgical gloves. Pre-donned, anatomically shaped. AQL 0.65 for sterile gloves. Gamma-irradiation sterilized. Available in sizes 6.0–8.5. Individually packed in double-wrap peel pouches. Meets EN455 all parts.',
    descriptionAr: 'قفازات جراحية معقمة خالية من المسحوق مصنوعة من المطاط الطبيعي.',
    price: 12.000,
    priceVat: 12.600,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/003B73/FFFFFF?text=Surgical+Gloves',
    ],
    stock: 120,
    unit: 'box',
    unitSize: '50 pairs',
    brand: 'SurgiShield',
    origin: 'Malaysia',
    tags: ['surgical gloves', 'sterile', 'latex', 'AQL 0.65', 'gamma sterilized'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['EN 455', 'CE', 'ISO 11135'],
    relatedIds: ['PPE-001', 'PPE-002'],
    createdAt: '2024-03-01',
  },

  // ─── DIAGNOSTICS ─────────────────────────────────────────────────────────────
  {
    id: 'DX-001',
    name: 'DigTherm Pro Non-Contact Thermometer',
    nameAr: 'ترمومتر لا تلامسي ديجي ثيرم برو',
    sku: 'HS-DX-001',
    category: 'diagnostics',
    subcategory: 'Temperature Monitoring',
    description: 'Infrared non-contact forehead thermometer with 0.1°C accuracy. Response time <1 second. Stores last 32 readings. Fever alarm at ≥37.5°C. Dual mode: body and object/surface. Backlit LCD display. Auto power-off. Calibration certificate included.',
    descriptionAr: 'ترمومتر جبهي بالأشعة تحت الحمراء بدقة 0.1 درجة مئوية. وقت استجابة أقل من ثانية.',
    price: 12.500,
    priceVat: 13.125,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/388E3C/FFFFFF?text=Thermometer',
    ],
    stock: 95,
    unit: 'piece',
    unitSize: 'With calibration cert.',
    brand: 'DigTherm',
    origin: 'South Korea',
    tags: ['thermometer', 'infrared', 'non-contact', 'fever', 'temperature'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'FDA', 'ISO 80601-2-56'],
    relatedIds: ['DX-002', 'DX-003'],
    createdAt: '2024-01-22',
  },
  {
    id: 'DX-002',
    name: 'OxyPulse Fingertip Pulse Oximeter',
    nameAr: 'جهاز قياس الأكسجين في الدم أوكسي بولس',
    sku: 'HS-DX-002',
    category: 'diagnostics',
    subcategory: 'Patient Monitoring',
    description: 'Portable fingertip pulse oximeter for SpO₂ and pulse rate measurement. ±2% SpO₂ accuracy. Measurement range: 70–100% SpO₂, 30–250 BPM. OLED display with 4-direction rotation. Low perfusion index alert. Plethysmograph waveform display. Batteries included.',
    descriptionAr: 'جهاز قياس تشبع الأكسجين ومعدل النبض بالإصبع. دقة SpO₂ ±2%.',
    price: 7.900,
    priceVat: 8.295,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/388E3C/FFFFFF?text=Pulse+Oximeter',
    ],
    stock: 140,
    unit: 'piece',
    unitSize: 'Batteries included',
    brand: 'OxyPulse',
    origin: 'China',
    tags: ['pulse oximeter', 'SpO2', 'oxygen saturation', 'BPM', 'OLED'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'FDA 510(k)', 'ISO 80601-2-61'],
    relatedIds: ['DX-001', 'DX-003'],
    createdAt: '2024-02-05',
  },
  {
    id: 'DX-003',
    name: 'ClearView Digital Blood Pressure Monitor',
    nameAr: 'جهاز قياس ضغط الدم الرقمي كليرفيو',
    sku: 'HS-DX-003',
    category: 'diagnostics',
    subcategory: 'Patient Monitoring',
    description: 'Validated upper-arm automatic blood pressure monitor. Measures systolic, diastolic and pulse rate. Memory: 2 × 60 readings. IHB detection. WHO hypertension colour indicator. Oscillometric measurement method. AC adapter + 4×AA batteries. Cuff size: 22–42cm.',
    descriptionAr: 'جهاز قياس ضغط الدم التلقائي بذراع الأعلى. يقيس الضغط الانقباضي والانبساطي ومعدل النبض.',
    price: 35.000,
    priceVat: 36.750,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/388E3C/FFFFFF?text=BP+Monitor',
    ],
    stock: 45,
    unit: 'piece',
    unitSize: 'With cuff 22-42cm',
    brand: 'ClearView',
    origin: 'Japan',
    tags: ['blood pressure', 'BP monitor', 'hypertension', 'oscillometric', 'IHB'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'ESH validated', 'BHS validated'],
    relatedIds: ['DX-001', 'DX-002'],
    createdAt: '2024-01-18',
  },

  // ─── STERILIZATION ───────────────────────────────────────────────────────────
  {
    id: 'ST-001',
    name: 'SteriPack Autoclave Pouches 89×230mm',
    nameAr: 'أكياس التعقيم ستيري باك 89×230 مم',
    sku: 'HS-ST-001',
    category: 'sterilization',
    subcategory: 'Sterilization Packaging',
    description: 'Self-sealing sterilization pouches for steam (134°C) and EO sterilization. Dual external chemical indicators (Type 1). Transparent side for instrument verification. Medical-grade paper back. Manufactured per EN ISO 11607. Box of 200 pouches.',
    descriptionAr: 'أكياس تعقيم ذاتية الإغلاق للتعقيم بالبخار (134 درجة) والإيثيلين أكسيد.',
    price: 6.750,
    priceVat: 7.088,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/4CAF50/FFFFFF?text=Autoclave+Pouches',
    ],
    stock: 200,
    unit: 'box',
    unitSize: '200 pouches',
    brand: 'SteriPack',
    origin: 'Netherlands',
    tags: ['autoclave pouches', 'sterilization', 'self-sealing', 'steam', 'EO'],
    featured: false,
    inStock: true,
    minOrderQty: 5,
    certifications: ['EN ISO 11607', 'CE'],
    relatedIds: ['ST-002', 'ST-003'],
    createdAt: '2024-02-25',
  },
  {
    id: 'ST-002',
    name: 'UV ProSterilizer Cabinet 30L',
    nameAr: 'خزانة التعقيم بالأشعة فوق البنفسجية 30 لتر',
    sku: 'HS-ST-002',
    category: 'sterilization',
    subcategory: 'UV Sterilization',
    description: 'Dual UV-C germicidal cabinet for dry instrument and tool storage after sterilization. 30-litre capacity with two UV-C lamps (254nm). Stainless steel interior. Timer 0–60 min. 360-degree UV exposure with bottom reflective tray. Not for primary sterilization — use for maintenance sterilization.',
    descriptionAr: 'خزانة جرثومية UV-C مزدوجة لتخزين الأدوات الجافة بعد التعقيم. سعة 30 لتر.',
    price: 125.000,
    priceVat: 131.250,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/4CAF50/FFFFFF?text=UV+Sterilizer',
    ],
    stock: 15,
    unit: 'piece',
    unitSize: '30 Litres',
    brand: 'UV ProSteril',
    origin: 'Taiwan',
    tags: ['UV sterilizer', 'UV-C', 'cabinet', 'germicidal', 'instrument storage'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'EMC'],
    relatedIds: ['ST-001', 'ST-003'],
    createdAt: '2024-03-10',
  },
  {
    id: 'ST-003',
    name: 'ProSteril Class B Autoclave 23L',
    nameAr: 'أوتوكلاف كلاس B برو ستيريل 23 لتر',
    sku: 'HS-ST-003',
    category: 'sterilization',
    subcategory: 'Steam Sterilizers',
    description: 'Vacuum Class B benchtop steam autoclave, 23-litre capacity. Pre-vacuum and post-vacuum cycles for porous loads, hollow instruments and wrapped items. 6 pre-programmed cycles: 121°C & 134°C. USB data logger. Traceability printing. Meets EN13060 Class B standard.',
    descriptionAr: 'أوتوكلاف بخاري كلاس B بسعة 23 لتر. دورات تفريغ أولية ولاحقة.',
    price: 850.000,
    priceVat: 892.500,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/4CAF50/FFFFFF?text=Autoclave+23L',
    ],
    stock: 5,
    unit: 'piece',
    unitSize: '23 Litres, 230V',
    brand: 'ProSteril',
    origin: 'Italy',
    tags: ['autoclave', 'Class B', 'steam sterilizer', 'benchtop', 'EN13060', 'vacuum'],
    featured: true,
    inStock: true,
    minOrderQty: 1,
    certifications: ['EN 13060 Class B', 'CE', 'MDD'],
    relatedIds: ['ST-001', 'ST-002'],
    createdAt: '2024-01-08',
  },

  // ─── MEDICAL DEVICES ─────────────────────────────────────────────────────────
  {
    id: 'MD-001',
    name: 'FlexiDraw Disposable Syringes 5ml',
    nameAr: 'محاقن استخدام واحد فليكسي دراو 5 مل',
    sku: 'HS-MD-001',
    category: 'medical-devices',
    subcategory: 'Injection & Infusion',
    description: 'Sterile disposable luer-lock syringes 5ml. Transparent barrel with clear graduation markings. Latex-free. Natural rubber piston for smooth plunger action. EO sterilized, gamma stable. Packed 100 per box. Compatible with all standard luer-lock needles.',
    descriptionAr: 'محاقن استخدام واحد معقمة بقفل لوير 5 مل. شفافة مع علامات تدرج واضحة.',
    price: 8.500,
    priceVat: 8.925,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/1976D2/FFFFFF?text=Syringes+5ml',
    ],
    stock: 250,
    unit: 'box',
    unitSize: '100 pcs',
    brand: 'FlexiDraw',
    origin: 'India',
    tags: ['syringe', 'disposable', 'luer-lock', 'sterile', '5ml'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'ISO 7886-1', 'FDA'],
    relatedIds: ['MD-002', 'IC-001'],
    createdAt: '2024-02-18',
  },
  {
    id: 'MD-002',
    name: 'MediPack Sterile Gauze Swabs 10×10cm',
    nameAr: 'شاش معقم ميدي باك 10×10 سم',
    sku: 'HS-MD-002',
    category: 'medical-devices',
    subcategory: 'Wound Care',
    description: 'Non-woven sterile gauze swabs for wound cleansing, dressing and packing. 10×10cm, 4-ply. Individually sealed in blister packs. Gamma sterilized. Lint-free, highly absorbent. X-ray detectable thread for surgical use. 100 packs of 2 swabs per box.',
    descriptionAr: 'شاش معقم غير منسوج لتنظيف وتضميد الجروح. 10×10 سم، 4 طبقات.',
    price: 3.800,
    priceVat: 3.990,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/1976D2/FFFFFF?text=Sterile+Gauze',
    ],
    stock: 350,
    unit: 'box',
    unitSize: '100 × 2-swab packs',
    brand: 'MediPack',
    origin: 'Turkey',
    tags: ['gauze', 'swabs', 'sterile', 'wound care', 'non-woven', 'x-ray detectable'],
    featured: false,
    inStock: true,
    minOrderQty: 5,
    certifications: ['CE', 'EN 13726', 'ISO 11135'],
    relatedIds: ['MD-001', 'MD-003'],
    createdAt: '2024-02-28',
  },
  {
    id: 'MD-003',
    name: 'ElasticCare Wound Dressing Assorted Pack',
    nameAr: 'حزمة ضمادات متنوعة إيلاستيك كير',
    sku: 'HS-MD-003',
    category: 'medical-devices',
    subcategory: 'Wound Care',
    description: 'Assorted hydrocolloid wound dressings for post-operative care and chronic wound management. 50 dressings in 4 sizes: 6×6cm, 10×10cm, 15×15cm, 10×20cm. Breathable, waterproof. Low-adherent inner layer. Stimulates moist wound healing environment. Up to 7-day wear.',
    descriptionAr: 'ضمادات هيدروكولويد متنوعة للعناية بما بعد العمليات وإدارة الجروح المزمنة.',
    price: 12.500,
    priceVat: 13.125,
    currency: 'OMR',
    images: [
      'https://placehold.co/600x600/1976D2/FFFFFF?text=Wound+Dressings',
    ],
    stock: 80,
    unit: 'pack',
    unitSize: '50 dressings, 4 sizes',
    brand: 'ElasticCare',
    origin: 'UK',
    tags: ['wound dressing', 'hydrocolloid', 'waterproof', 'chronic wound', 'post-operative'],
    featured: false,
    inStock: true,
    minOrderQty: 1,
    certifications: ['CE', 'EN 13726'],
    relatedIds: ['MD-001', 'MD-002'],
    createdAt: '2024-03-08',
  },
]

// Helpers
export const getProductById = (id: string): Product | undefined =>
  PRODUCTS.find((p) => p.id === id)

export const getProductsByCategory = (category: string): Product[] =>
  PRODUCTS.filter((p) => p.category === category)

export const getFeaturedProducts = (): Product[] =>
  PRODUCTS.filter((p) => p.featured)

export const getCategoryById = (id: string): Category | undefined =>
  CATEGORIES.find((c) => c.id === id)

export const searchProducts = (query: string): Product[] => {
  const q = query.toLowerCase()
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.includes(q)
  )
}
